version: '3'
services:
  db:
    container_name: sql2019
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    volumes:
      - mssql_data:/var/opt/mssql
    ports:
      - 1433:1433
    networks:
      - java-mssql
    restart: always
  web:
    container_name: easkb2
    image: vuhuyenmily/easkb2:v1.0
    ports:
      - 8080:8080
    networks:
      - java-mssql
    depends_on:
      - db  
volumes:
  mssql_data:
networks:
  java-mssql:
    
