version: '3'
services:
  db:
    container_name: sqledge
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'Super5ecret!'
    volumes:
      - mssql_data:/var/opt/mssql
    ports:
      - 1433:1433
    networks:
      - java-mssql
    restart: always
  web:
    container_name: easkb2
    image: vuhuyenmily/easkb2:v1.0
    ports:
      - 8080:8080
    networks:
      - java-mssql
    depends_on:
      - db
volumes:
  mssql_data:
networks:
  java-mssql:
    
